name: linux

on:
  pull_request:
  push:

jobs:
  create_dev_release:
    runs-on: ubuntu-22.04
    steps:
    - name: Create Development release
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/vanilla' }}
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        
  vanilla-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [clang, gcc]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Set Git Info
      id: gitinfo
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Set variables
      id: vars
      run: |
        if [ "${{ matrix.platform }}" = "clang" ]
        then
          echo "::set-output name=cc::clang"
          echo "::set-output name=cxx::clang++"
        else
          echo "::set-output name=cc::gcc"
          echo "::set-output name=cxx::g++"
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update -qq > /dev/null
        sudo apt-get install -qq -y clang-format-12 libsdl2-dev libopenal-dev > /dev/null

    - name: Configure Vanilla Conquer
      env:
          CC: ${{ steps.vars.outputs.cc }}
          CXX: ${{ steps.vars.outputs.cxx }}
      run: |
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMAP_EDITORTD=ON -DMAP_EDITORRA=ON -DBUILD_TOOLS=ON -DBUILD_TESTS=ON -B build

    - name: Check formatting
      if: ${{ matrix.platform }} == clang
      run: |
        cmake --build build --target format
        git diff --exit-code
        
    - name: Build Vanilla Conquer
      run: |
        cmake --build build -- -j 4
        cp ./build/vanillatd ./build/vanillatd.dbg
        cp ./build/vanillara ./build/vanillara.dbg
        cp ./build/vanillamix ./build/vanillamix.dbg
        strip --strip-all ./build/vanillatd
        strip --strip-all ./build/vanillara
        strip --strip-all ./build/vanillamix
        objcopy --add-gnu-debuglink=./build/vanillatd.dbg ./build/vanillatd
        objcopy --add-gnu-debuglink=./build/vanillara.dbg ./build/vanillara
        objcopy --add-gnu-debuglink=./build/vanillamix.dbg ./build/vanillamix

    - name: Run unit tests
      run: |
        cd build
        ctest

    - name: Create archives
      run: |
        mkdir artifact
        7z a artifact/vanilla-conquer-linux-${{ matrix.platform }}-x86_64-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/vanillatd ./build/vanillara ./build/vanillamix
        7z a artifact/vanilla-conquer-linux-${{ matrix.platform }}-x86_64-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/vanillatd.dbg ./build/vanillara.dbg ./build/vanillamix.dbg

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: vanilla-conquer-linux-${{ matrix.platform }}-x86_64
        path: artifact
        
    - name: Upload development release
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/vanilla' }}
      uses: softprops/action-gh-release@v1
      with:
        name: Development Build
        tag_name: "latest"
        prerelease: true
        files: |
          artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload tagged release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
